In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset4/main/Grades.csv')
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [3]:
df.head()

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448

In [4]:
df['PH-121'].unique

<bound method Series.unique of 0      B-
1       A
2       A
3       D
4      A-
       ..
566     B
567    A+
568     B
569     A
570     C
Name: PH-121, Length: 571, dtype: object>

In [7]:
df['PH-121'].value_counts()

A-    112
A     111
B+     61
B      57
B-     56
D      44
C      33
C+     31
D+     22
A+     22
C-     19
WU      2
F       1
Name: PH-121, dtype: int64

In [9]:
df.dtypes

Seat No.      object
PH-121        object
HS-101        object
CY-105        object
HS-105/12     object
MT-111        object
CS-105        object
CS-106        object
EL-102        object
EE-119        object
ME-107        object
CS-107        object
HS-205/20     object
MT-222        object
EE-222        object
MT-224        object
CS-210        object
CS-211        object
CS-203        object
CS-214        object
EE-217        object
CS-212        object
CS-215        object
MT-331        object
EF-303        object
HS-304        object
CS-301        object
CS-302        object
TC-383        object
MT-442        object
EL-332        object
CS-318        object
CS-306        object
CS-312        object
CS-317        object
CS-403        object
CS-421        object
CS-406        object
CS-414        object
CS-419        object
CS-423        object
CS-412        object
CGPA         float64
dtype: object

In [10]:
df.replace({'A':2,'A+':1,'A-':3,'B+':4,'B':5,'B-':6,'C+':7,'C':8,'C-':9,'D+':10,'D':11,'D-':12,'F':0,'WU':0},inplace=True)

In [11]:
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,6,10,9.0,8.0,9.0,10,11.0,9.0,6.0,...,9,9.0,9.0,9,3,2,9.0,5.0,3,2.205
1,CS-97002,2,11,10.0,11.0,6.0,8,11.0,2.0,10.0,...,10,11.0,8.0,11,3,6,8.0,8.0,5,2.008
2,CS-97003,2,5,2.0,6.0,4.0,2,6.0,4.0,3.0,...,5,5.0,2.0,8,2,2,2.0,3.0,2,3.608
3,CS-97004,11,7,10.0,11.0,11.0,3,10.0,9.0,11.0,...,10,8.0,10.0,9,6,5,7.0,7.0,7,1.906
4,CS-97005,3,3,3.0,4.0,2.0,2,3.0,4.0,2.0,...,6,4.0,4.0,6,3,2,3.0,3.0,2,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,5,2,2.0,3.0,1.0,2,3.0,3.0,1.0,...,3,3.0,2.0,2,2,4,4.0,5.0,2,3.798
567,CS-97568,1,2,2.0,2.0,2.0,2,2.0,3.0,2.0,...,4,4.0,2.0,2,3,5,3.0,8.0,3,3.772
568,CS-97569,5,2,3.0,4.0,2.0,2,2.0,2.0,2.0,...,3,5.0,2.0,4,2,8,4.0,3.0,3,3.470
569,CS-97570,2,4,11.0,2.0,11.0,10,6.0,9.0,6.0,...,11,5.0,5.0,9,11,8,5.0,6.0,8,2.193
570,CS-97571,8,11,11.0,8.0,8.0,10,5.0,7.0,8.0,...,7,8.0,6.0,11,0,9,4.0,11.0,9,1.753

In [14]:
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,2,C-,B,A-,2.205
1,CS-97002,2,D,D+,D,B-,C,D,2,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,2,B,2,B-,B+,2,B-,B+,A-,...,B,B,2,C,2,2,2,A-,2,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,2,2,A-,B+,2,...,B-,B+,B+,B-,A-,2,A-,A-,2,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,2,2,A-,A+,2,A-,A-,A+,...,A-,A-,2,2,2,B+,B+,B,2,3.798
567,CS-97568,A+,2,2,2,2,2,2,A-,2,...,B+,B+,2,2,A-,B,A-,C,A-,3.772
568,CS-97569,B,2,A-,B+,2,2,2,2,2,...,A-,B,2,B+,2,C,B+,A-,A-,3.470
569,CS-97570,2,B+,D,2,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [15]:
df.isnull().sum()

Seat No.      0
PH-121        0
HS-101        0
CY-105        1
HS-105/12     1
MT-111        2
CS-105        0
CS-106        2
EL-102        2
EE-119        2
ME-107        2
CS-107        2
HS-205/20     5
MT-222        5
EE-222        7
MT-224        7
CS-210        7
CS-211        5
CS-203        5
CS-214        6
EE-217        6
CS-212        6
CS-215        6
MT-331        9
EF-303       10
HS-304       10
CS-301       10
CS-302       10
TC-383       10
MT-442       10
EL-332        9
CS-318        9
CS-306        9
CS-312       10
CS-317       12
CS-403       12
CS-421       12
CS-406       85
CS-414       13
CS-419       13
CS-423       14
CS-412       79
CGPA          0
dtype: int64

In [19]:
df['CY-105'].unique()

array(['C-', 'D+', 2, 'A-', 'B', 'C+', 'B+', 'B-', 'C', 'D', nan, 'WU',
       'A+', 'F'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
x=df.drop('CGPA',axis=True)
y=df['CGPA']

In [11]:
x

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D,D+,D,C,D,A-,B-,C,C,B
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,A-,B,B,A,C,A,A,A,A-,A
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,B+,D,B,B,C-,D,C,B,B-,C
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [9]:
le=LabelEncoder()
df_e=le.fit_transform(df['PH-121','HS-101'])
pd.Series(df_e)

KeyError: ('PH-121', 'HS-101')